// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjc6IjAQ2SQiDWar42LcR9xd8rn6f--aE',
    appId: '1:5943082463:web:c6f15b5b6bba80eb7e586a',
    messagingSenderId: '5943082463',
    projectId: 'almisa-ticaret',
    authDomain: 'almisa-ticaret.firebaseapp.com',
    storageBucket: 'almisa-ticaret.appspot.com',
    measurementId: 'G-SF4ZEQENS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0MtQrsV8glOR82AtKO9WybAN9JAobqs',
    appId: '1:5943082463:android:84e96b3866fd87907e586a',
    messagingSenderId: '5943082463',
    projectId: 'almisa-ticaret',
    storageBucket: 'almisa-ticaret.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb5Ewh0UL0rc2AN00UhiGwOfx3rrLkdpk',
    appId: '1:5943082463:ios:d0a84af27870716c7e586a',
    messagingSenderId: '5943082463',
    projectId: 'almisa-ticaret',
    storageBucket: 'almisa-ticaret.appspot.com',
    iosClientId:
        '5943082463-oiauj4l4mcbtgihi5e15rhsc58tnuj88.apps.googleusercontent.com',
    iosBundleId: 'com.example.tedarikq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb5Ewh0UL0rc2AN00UhiGwOfx3rrLkdpk',
    appId: '1:5943082463:ios:d0a84af27870716c7e586a',
    messagingSenderId: '5943082463',
    projectId: 'almisa-ticaret',
    storageBucket: 'almisa-ticaret.appspot.com',
    iosClientId:
        '5943082463-oiauj4l4mcbtgihi5e15rhsc58tnuj88.apps.googleusercontent.com',
    iosBundleId: 'com.example.tedarikq',
  );
}
